name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # every week on Sunday

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} / ActiveRecord ${{ matrix.activerecord }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - 'head'
        activerecord:
          - '2.3'
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: makara_test
          RUBYOPT: -W0
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rspec
        env:
          MYSQL_HOST: 127.0.0.1
          RAILS_ENV: test
      - name: Archive coverage artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.ruby }}
          path: coverage/
          retention-days: 7
